import { useEffect, useState } from 'react'
import api from '../../services/api'
import StatusBadge from '../../components/shared/StatusBadge'
import { PageLoader } from '../../components/shared/LoadingSpinner'
import EmptyState from '../../components/shared/EmptyState'
import { ReceiptIcon } from '../../components/shared/Icons'

export default function Invoices() {
  const [invoices, setInvoices] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.get('/invoices').then(({ data }) => setInvoices(data.data.invoices))
      .catch(() => {}).finally(() => setLoading(false))
  }, [])

  if (loading) return <PageLoader />

  return (
    <div className="max-w-4xl space-y-4">
      <h1 className="text-xl font-bold text-zinc-900">Invoices</h1>

      <div className="card overflow-hidden">
        {invoices.length === 0 ? (
          <EmptyState icon={<ReceiptIcon className="h-12 w-12" />} title="No invoices yet" description="Invoices will appear here once generated by ShipEase." />
        ) : (
          <>
            <div className="hidden md:block overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-zinc-100 bg-zinc-50">
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Invoice No</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Period</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Amount</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Date</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {invoices.map(inv => (
                    <tr key={inv.id} className="border-b border-zinc-50 hover:bg-zinc-50">
                      <td className="px-6 py-4 font-mono font-semibold text-zinc-900">{inv.invoiceNo}</td>
                      <td className="px-6 py-4 text-zinc-600">
                        {new Date(inv.dateFrom).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} –{' '}
                        {new Date(inv.dateTo).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </td>
                      <td className="px-6 py-4 font-semibold text-zinc-900">₹{Number(inv.totalAmount).toLocaleString('en-IN')}</td>
                      <td className="px-6 py-4"><StatusBadge status={inv.status} /></td>
                      <td className="px-6 py-4 text-zinc-500">{new Date(inv.createdAt).toLocaleDateString('en-IN')}</td>
                      <td className="px-6 py-4">
                        {inv.pdfUrl ? (
                          <a href={`/api/invoices/${inv.id}/download`} target="_blank" rel="noreferrer"
                            className="inline-flex items-center gap-1 text-xs font-semibold text-red-600 hover:text-red-700">
                            <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            PDF
                          </a>
                        ) : <span className="text-xs text-zinc-400">Not ready</span>}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Mobile cards */}
            <div className="md:hidden space-y-3 p-4">
              {invoices.map(inv => (
                <div key={inv.id} className="rounded-lg border border-zinc-200 bg-white p-4">
                  <div className="flex items-start justify-between gap-2">
                    <p className="font-mono text-xs font-semibold text-zinc-900">{inv.invoiceNo}</p>
                    <StatusBadge status={inv.status} />
                  </div>
                  <p className="mt-1 text-sm font-semibold text-zinc-900">₹{Number(inv.totalAmount).toLocaleString('en-IN')}</p>
                  <p className="text-xs text-zinc-500">
                    {new Date(inv.dateFrom).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} –{' '}
                    {new Date(inv.dateTo).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
                  </p>
                  <div className="mt-2 flex items-center justify-between">
                    <p className="text-xs text-zinc-400">{new Date(inv.createdAt).toLocaleDateString('en-IN')}</p>
                    {inv.pdfUrl ? (
                      <a href={`/api/invoices/${inv.id}/download`} target="_blank" rel="noreferrer"
                        className="inline-flex items-center gap-1 text-xs font-semibold text-red-600 hover:text-red-700">
                        <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        PDF
                      </a>
                    ) : <span className="text-xs text-zinc-400">Not ready</span>}
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}
